// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArIOgSC4pDpvM5fZBjjXWvSb8w_YInlY8',
    appId: '1:849271738337:android:54e652de699e6762b18ca0',
    messagingSenderId: '849271738337',
    projectId: 'healthcare-f91fb',
    databaseURL: 'https://healthcare-f91fb-default-rtdb.firebaseio.com',
    storageBucket: 'healthcare-f91fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsnyT-7KPZ6wNY8co3Sm0mV33Kmf7i3Ss',
    appId: '1:849271738337:ios:5076785f58977d94b18ca0',
    messagingSenderId: '849271738337',
    projectId: 'healthcare-f91fb',
    databaseURL: 'https://healthcare-f91fb-default-rtdb.firebaseio.com',
    storageBucket: 'healthcare-f91fb.appspot.com',
    iosBundleId: 'com.example.care',
  );
}
